/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_errnotab.c                                      :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: maldavid <kbz_8.dev@akel-engine.com>       +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/07/27 17:06:25 by maldavid          #+#    #+#             */
/*   Updated: 2022/08/08 13:37:11 by maldavid         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "libft_internal.h"

const char	*g_errno_tab[103] = {
	"ft_errno : Operation not permitted",
	"ft_errno : No such file or directory",
	"ft_errno : No such process",
	"ft_errno : Interrupted system call",
	"ft_errno : Input/output error",
	"ft_errno : No such device or address",
	"ft_errno : Argument list too long",
	"ft_errno : Exec format error",
	"ft_errno : Bad file descriptor",
	"ft_errno : No child processes",
	"ft_errno : Resource deadlock avoided",
	"ft_errno : Cannot allocate memory",
	"ft_errno : Permission denied",
	"ft_errno : Bad address",
	"ft_errno : Block device required",
	"ft_errno : Device or resource busy",
	"ft_errno : File exists",
	"ft_errno : Invalid cross-device link",
	"ft_errno : No such device",
	"ft_errno : Not a directory",
	"ft_errno : Is a directory",
	"ft_errno : Invalid argument",
	"ft_errno : Too many open files",
	"ft_errno : Too many open files in system",
	"ft_errno : Inappropriate ioctl for device",
	"ft_errno : Text file busy",
	"ft_errno : File too large",
	"ft_errno : No space left on device",
	"ft_errno : Illegal seek",
	"ft_errno : Read-only file system",
	"ft_errno : Too many links",
	"ft_errno : Broken pipe",
	"ft_errno : Numerical argument out of domain",
	"ft_errno : Numerical result out of range",
	"ft_errno : Resource temporarily unavailable",
	"ft_errno : Operation now in progress",
	"ft_errno : Operation already in progress",
	"ft_errno : Socket operation on non-socket",
	"ft_errno : Message too long",
	"ft_errno : Protocol wrong type for socket",
	"ft_errno : Protocol not available",
	"ft_errno : Protocol not supported",
	"ft_errno : Socket type not supported",
	"ft_errno : Operation not supported",
	"ft_errno : Protocol family not supported",
	"ft_errno : Address family not supported by protocol",
	"ft_errno : Address already in use",
	"ft_errno : Cannot assign requested address",
	"ft_errno : Network is down",
	"ft_errno : Network is unreachable",
	"ft_errno : Network dropped connection on reset",
	"ft_errno : Software caused connection abort",
	"ft_errno : Connection reset by peer",
	"ft_errno : No buffer space available",
	"ft_errno : Transport endpoint is already connected",
	"ft_errno : Transport endpoint is not connected",
	"ft_errno : Destination address required",
	"ft_errno : Cannot send after transport endpoint shutdown",
	"ft_errno : Too many references: cannot splice",
	"ft_errno : Connection timed out",
	"ft_errno : Connection refused",
	"ft_errno : Too many levels of symbolic links",
	"ft_errno : File name too long",
	"ft_errno : Host is down",
	"ft_errno : No route to host",
	"ft_errno : Directory not empty",
	"ft_errno : Too many processes",
	"ft_errno : Too many users",
	"ft_errno : Disk quota exceeded",
	"ft_errno : Stale file handle",
	"ft_errno : Object is remote",
	"ft_errno : RPC struct is bad",
	"ft_errno : RPC version wrong",
	"ft_errno : RPC program not available",
	"ft_errno : RPC program version wrong",
	"ft_errno : RPC bad procedure for program",
	"ft_errno : No locks available",
	"ft_errno : Inappropriate file type or format",
	"ft_errno : Authentication error",
	"ft_errno : Need authenticator",
	"ft_errno : Function not implemented",
	"ft_errno : Not supported",
	"ft_errno : Invalid or incomplete multibyte or wide character",
	"ft_errno : Inappropriate operation for background process",
	"ft_errno : Translator died",
	"ft_errno : ?",
	"ft_errno : You really blew it this time",
	"ft_errno : Computer bought the farm",
	"ft_errno : Gratuitous error",
	"ft_errno : Bad message",
	"ft_errno : Identifier removed",
	"ft_errno : Multihop attempted",
	"ft_errno : No data available",
	"ft_errno : Link has been severed",
	"ft_errno : No message of desired type",
	"ft_errno : Out of streams resources",
	"ft_errno : Device not a stream",
	"ft_errno : Value too large for defined data type",
	"ft_errno : Protocol error",
	"ft_errno : Timer expired",
	"ft_errno : Operation canceled",
	"ft_errno : Owner died",
	"ft_errno : State not recoverable",
};
